### PR TITLE
update zh_cn.json

### PR DESCRIPTION
**Pull request by x-yingcan-x**

### CODE REVIEW

**Comment by x-yingcan-x** [comment]
Sorry,Do you want to help me solve a problem?
It's not cause be VFP.But won't appear in older version and I have no idea about the solution.
I tried only use VFP.[latest.log](https://github.com/ViaVersion/ViaFabricPlus/files/11781382/latest.log)

**Comment by FlorianMichael** [comment]
You are using Minecraft Forge?

**Comment by x-yingcan-x** [comment]
No,fabric
1.20.1 fabric -> 1.12.2 server

**Comment by FlorianMichael** [comment]
So this log file is from the server?

**Comment by x-yingcan-x** [comment]
[latest.log](https://github.com/ViaVersion/ViaFabricPlus/files/11781455/latest.log)
I upload the wrong one

**Comment by FlorianMichael** [comment]
The rendering errors are pretty sure not due to VFP, just remove your mods until the error is no longer there.

**Comment by x-yingcan-x** [comment]
Sorry I do many thing in a mess.wait a minute

**Comment by FlorianMichael** [comment]
Please join my Discord, then you can write me there further

**Comment by x-yingcan-x** [comment]
But I am unable to use Discord as I'm a chinese and discord is blocked

**Comment by x-yingcan-x** [comment]
check those [anti packet kick] lines [latest.log](https://github.com/ViaVersion/ViaFabricPlus/files/11781464/latest.log)
I use meteor to pravent from disconnect

**Comment by FlorianMichael** [comment]
I have no idea

**Comment by x-yingcan-x** [comment]
Anyway ,thanks.

**Pull request merged**
