### PR TITLE
Add toggle for bubble pop sound/icons

### PR DESCRIPTION
**Pull request by lowercasebtw**
Adds 2 toggles for <=1.21.1 to remove the annoying bubble pop sound/visual

### CODE REVIEW

**Comment by RaphiMC** [comment]
I don't think its a good idea to remove useful and functional game features. Else ViaFabricPlus would also have to revert the potion HUD overlay

**Comment by lowercasebtw** [comment]
Thats why its a toggle

**Comment by lowercasebtw** [comment]
Also the bubble sound is annoying to some

**Comment by lowercasebtw** [comment]
Yall hide hunger/xp for <=b1.7.3 & other stuff

**Comment by RaphiMC** [comment]
> Yall hide hunger/xp for <=b1.7.3 & other stuff

because those don't work. the air bubbles do work tho

**Comment by RaphiMC** [comment]
> Thats why its a toggle

Your current implementation would disable the sound/empty bubble icon by default when using older versions, which isn't good

**Comment by lowercasebtw** [comment]
then ill change that

**Comment by lowercasebtw** [comment]
Fixed

**Review by RaphiMC — APPROVED** [review]

**Review by FlorianMichael — APPROVED** [review]

**Pull request merged**
