### PR TITLE
Fix ClientPlayerInteractionManager#interactBlockInternal for 1.21

### PR DESCRIPTION
**Pull request by CrashSystemZ**

### CODE REVIEW

**Review by FlorianMichael — CHANGES_REQUESTED** [review]
What exactly does this fix? It looks quite wrong as you are basically removing any interactions here

**Comment by CrashSystemZ** [comment]
when you go from version 1.21 to servers where version 1.16, but there is ViaVersion and right-click on the blocks, you are immediately kicked from the server, because on versions before 1.21, there was literally nothing (in the place where I added PASS), but on 1.21 there added some changes

**Comment by FlorianMichael** [comment]
1.20.6 to 1.21 hasn't changed anything in the ClientPlayerInteractionManager except removing the idle packet in useItem, this PR is in any case either completely wrong or things are missing. I saw that there were interaction changes in 1.20.3 to 1.20.5 but I think this is same I will take care of myself once we finish 1.20.5 fixes.

**Comment by CrashSystemZ** [comment]
OK, I'm wrong and the changes appeared already in 1.20.5-6, but they appeared and the servers react negatively to it, so I'm waiting for a fix then already from you.

**Pull request closed without merging**
