### PR TITLE
Update JitPack, Loom 1.9

### PR DESCRIPTION
**Pull request by Kichura**
1. Update JDK to 21.0.5 in JitPack,
2. Updates Fabric Loom to 1.9+ to address Gradle-related issues in terms of building.

### CODE REVIEW

**Comment by FlorianMichael** [comment]
The main branch is freezed at the moment in favour of the v4.0.0 branch.

**Comment by Kichura** [comment]
Cancelling my issue then as loom is already up-to-date tho jitpack isn't but do whatever with it.

**Comment by FlorianMichael** [comment]
I planned on removing jitpack soon as it won't work with the new project structure + we have our own repository server.

**Comment by Kichura** [comment]
is it the [Jenkins Server](https://ci.viaversion.com) or what's the source of it?

**Comment by FlorianMichael** [comment]
As far as I know, jitpack doesn't support multi project builds, meaning people won't be able to include **viafabricplus-api** which will exist after v4. Ideally they should use https://repo.viaversion.com/#/ then

**Comment by Kichura** [comment]
Will plan on discontinuing it in baseproject then.

**Pull request closed without merging**
