### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by x-yingcan-x**

### CODE REVIEW

**Comment by FlorianMichael** [comment]
Please remove the // comment, this is not allowed in json

**Comment by x-yingcan-x** [comment]
I remember it allowed ,at least it works normally without any mod else

**Comment by FlorianMichael** [comment]
Okay, actually Json should not be able to do that, well never mind

**Comment by Earthcomputer** [comment]
Gson allows comments even in strict mode. See [this issue](https://github.com/google/gson/issues/212)

**Pull request merged**
