### PR TITLE
Fix #106

### LINKED ISSUE #106: Add translations for the configuration's group names
I noticed, that there are no translations available for the config's group names.  
  
I've tried to implement it myself, but (I'm writing it from memory, it was a few months ago or sth) the group name is passed to the constructor of some class, and I wanted to wait until the minecraft resource manager loads in, but it wasn't possible since that class was already used somewhere else in the code before the minecraft resource manager loads in. I just don't want to dip my toes in that shit so I will leave it as an "enhancement" issue here.  
  
I hope somebody will implement it.

### PR DESCRIPTION
**Pull request by Blayung**
I've managed to do it myself

### CODE REVIEW

**Comment by Blayung** [comment]
Actually, I do not really like one thing. Just hold on merging a little bit.

**Comment by Blayung** [comment]
Ok, I have decided to leave it out without refactoring. The "name" name is kinda undescriptive, but whatever.  
  
But I have found a bug! Good that I looked at the code again. I think it's ready to merge.

**Comment by FlorianMichael** [comment]
The changes just don't fit into my codestyle, whenever there are translations I pass a Text object and not a String, also I never add translations in other languages than English, because otherwise no one would ever notice that they still need to be translated.

**Comment by Blayung** [comment]
Passing it as a string was actually pretty dumb. I also deleted the translation keys. Is it good now?

**Comment by FlorianMichael** [comment]
No, you should make a text field as parameter in the constructor of the setting groups

**Comment by FlorianMichael** [comment]
Example:
```java 
public AuthenticationSettings() {
        super(Text.translatable("settings.viafabricplus.authentication"));
}
```

**Comment by FlorianMichael** [comment]
Thanks!

**Comment by Blayung** [comment]
Btw when did that repo get moved to ViaVersion?

**Comment by FlorianMichael** [comment]
One two days ago, ViaForge, ViaProxy, ViaLegacy and ViaAprilFools are now also on the organization, is just better when everything belongs together

**Comment by Kichura** [comment]
a bit of an off-topic comment: now imagine if geyser and floodgate were in this organization too.

**Comment by Blayung** [comment]
now imagine it's merged into a single mod

**Comment by Blayung** [comment]
and the whole world is so much better

**Comment by Blayung** [comment]
But really, it'd be a nice center for minecraft cross-version playing. We could also add TunnelMC here, although I'm not sure if it's even still supported (but I bumped into such project in the past).

**Comment by Blayung** [comment]
But these projects have no affilation with ViaVersion, so I don't think it's gonna happen.

**Comment by FlorianMichael** [comment]
TunnelMC is long dead, as soon as ViaBedrock by RaphiMC is far enough, it will be moved here too, but if you want to write about something like that, please come to Discord and in #off-topic

**Pull request merged**
